version: "3.8"

services:
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    ports:
      - 9091:9091
    volumes:
      - /config:/config
    environment:
      - TZ=America/Chicago