version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /vaultwarden:/data/
      #- dockerdata:/data/
      #- type: volume
        #source: dockerdata
        #target: data
    ports:
      - 8005:80

#volumes:
  #vaultwarden: