version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: https://ntfy.site.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: write-only
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh #for ios notifications
      NTFY_WEB_PUSH_PUBLIC_KEY: <public_key> #leave unless you know what you are doing
      NTFY_WEB_PUSH_PRIVATE_KEY: <private_key> #leave unless you know what you are doing
      NTFY_WEB_PUSH_FILE: /var/lib/ntfy/webpush.db #leave unless you know what you are doing
      NTFY_WEB_PUSH_EMAIL_ADDRESS: <email>
    volumes:
      - ./:/var/lib/ntfy
    ports:
      - 7300:80
    command: serve
