---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /config:/config
      - /downloads:/downloads #optional
    ports:
      - 7877:7878
    restart: unless-stopped