version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_SCHEDULE=0 0 4 * * * #cron schedule set for 4am everyday
      #Notification setup for ntfy
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=ntfy://<ntfy.sh site>/watchtower?title=watchtower #make sure in ntfy container you set NTFY_AUTH_DEFAULT_ACCESS to write-only
    #command: --interval 30
